# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{extjs-theme}
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Christopher Scott"]
  s.date = %q{2010-02-12}
  s.default_executable = %q{xtheme}
  s.description = %q{Generates Sass-based Ext themes.  Includes methods for colorizing themes.}
  s.email = %q{christocracy@gmail.com}
  s.executables = ["xtheme"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README",
     "README.rdoc"
  ]
  s.files = [
    "Rakefile",
     "bin/xtheme",
     "lib/extjs-theme.rb",
     "lib/extjs-theme/command.rb",
     "lib/extjs-theme/commands/base.rb",
     "lib/extjs-theme/commands/conifg.rb",
     "lib/extjs-theme/commands/effects.rb",
     "lib/extjs-theme/commands/help.rb",
     "lib/extjs-theme/commands/theme.rb",
     "lib/extjs-theme/dependencies.rb",
     "lib/extjs-theme/effects.rb",
     "lib/extjs-theme/generator.rb",
     "lib/extjs-theme/template/defines.sass",
     "test/extjs-xtheme_test.rb",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/extjs/extjs-theme}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Ext theme-generator and colorizer}
  s.test_files = [
    "test/extjs-xtheme_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
      s.add_runtime_dependency(%q<rmagick>, [">= 0"])
      s.add_runtime_dependency(%q<haml-edge>, [">= 2.3"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
      s.add_dependency(%q<rmagick>, [">= 0"])
      s.add_dependency(%q<haml-edge>, [">= 2.3"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    s.add_dependency(%q<rmagick>, [">= 0"])
    s.add_dependency(%q<haml-edge>, [">= 2.3"])
  end
end
