# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{extjs-xtheme}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Christocracy"]
  s.date = %q{2010-02-12}
  s.default_executable = %q{xtheme}
  s.description = %q{TODO: longer description of your gem}
  s.email = %q{christocracy@gmail.com}
  s.executables = ["xtheme"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README",
     "README.rdoc"
  ]
  s.files = [
    "Rakefile",
     "bin/xtheme",
     "lib/extjs-xtheme.rb",
     "lib/extjs-xtheme/command.rb",
     "lib/extjs-xtheme/commands/base.rb",
     "lib/extjs-xtheme/commands/conifg.rb",
     "lib/extjs-xtheme/commands/help.rb",
     "lib/extjs-xtheme/commands/theme.rb",
     "lib/extjs-xtheme/dependencies.rb",
     "lib/extjs-xtheme/effects.rb",
     "lib/extjs-xtheme/generator.rb",
     "lib/extjs-xtheme/template/defines.sass",
     "test/extjs-xtheme_test.rb",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/christocracy/extjs-xtheme}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{TODO: one-line summary of your gem}
  s.test_files = [
    "test/extjs-xtheme_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
      s.add_runtime_dependency(%q<rmagick>, [">= 0"])
      s.add_runtime_dependency(%q<haml-edge>, [">= 2.3"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
      s.add_dependency(%q<rmagick>, [">= 0"])
      s.add_dependency(%q<haml-edge>, [">= 2.3"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    s.add_dependency(%q<rmagick>, [">= 0"])
    s.add_dependency(%q<haml-edge>, [">= 2.3"])
  end
end
